"""add viajes evidencias incidentes

Revision ID: 3d72b5cbfcec
Revises: ac0fbde68e08
Create Date: 2026-03-03 03:05:54.643561

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d72b5cbfcec'
down_revision: Union[str, None] = 'ac0fbde68e08'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('viajes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_viaje', sa.String(length=80), nullable=False),
    sa.Column('cliente', sa.String(length=200), nullable=False),
    sa.Column('origen', sa.String(length=200), nullable=False),
    sa.Column('destino', sa.String(length=200), nullable=False),
    sa.Column('trailer', sa.String(length=80), nullable=False),
    sa.Column('caja', sa.String(length=80), nullable=False),
    sa.Column('tipo_carga', sa.String(length=120), nullable=True),
    sa.Column('peso_caja', sa.Float(), nullable=True),
    sa.Column('fecha_salida', sa.DateTime(), nullable=False),
    sa.Column('fecha_entrega_programada', sa.Date(), nullable=True),
    sa.Column('combustible_salida', sa.Float(), nullable=True),
    sa.Column('kilometraje_salida', sa.Integer(), nullable=True),
    sa.Column('fecha_entregada', sa.Date(), nullable=True),
    sa.Column('sellos_recibido', sa.String(length=200), nullable=True),
    sa.Column('claves_maniobra_dhl', sa.String(length=200), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_viajes_id_viaje'), 'viajes', ['id_viaje'], unique=False)
    op.create_table('evidencias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('viaje_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('descripcion', sa.String(length=200), nullable=True),
    sa.Column('file_url', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['viaje_id'], ['viajes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('incidentes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('viaje_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=30), nullable=False),
    sa.Column('lugar', sa.String(length=200), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['viaje_id'], ['viajes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('incidentes')
    op.drop_table('evidencias')
    op.drop_index(op.f('ix_viajes_id_viaje'), table_name='viajes')
    op.drop_table('viajes')
    # ### end Alembic commands ###
